In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 

import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv(
    r'C:\Users\PCUser\Downloads\Actual_generation_Germany.csv',
    sep=';',
    encoding='utf-8-sig',  
    thousands=',',         
    decimal='.'            
)

print(df.shape)
print(df.dtypes)
print(df.head(2))

(282432, 14)
Start date                                             str
End date                                               str
Biomass [MWh] Original resolutions                 float64
Hydropower [MWh] Original resolutions              float64
Wind offshore [MWh] Original resolutions           float64
Wind onshore [MWh] Original resolutions            float64
Photovoltaics [MWh] Original resolutions           float64
Other renewable [MWh] Original resolutions         float64
Nuclear [MWh] Original resolutions                  object
Lignite [MWh] Original resolutions                 float64
Hard coal [MWh] Original resolutions               float64
Fossil gas [MWh] Original resolutions              float64
Hydro pumped storage [MWh] Original resolutions    float64
Other conventional [MWh] Original resolutions       object
dtype: object
             Start date              End date  \
0  Apr 1, 2018 12:00 AM  Apr 1, 2018 12:15 AM
1  Apr 1, 2018 12:15 AM  Apr 1, 2018 12:30 AM

   Biomass [MWh] Original resolutions  Hydropower [MWh] Original resolutions  \
0                              1173.0                                 422.75
1                              1160.0                                 421.00

   Wind offshore [MWh] Original resolutions  \
0                                    410.00
1                                    399.75

   Wind onshore [MWh] Original resolutions  \
0                                   1743.5
1                                   1812.5

   Photovoltaics [MWh] Original resolutions  \
0                                       0.0
1                                       0.0

   Other renewable [MWh] Original resolutions  \
0                                       59.75
1                                       59.75

  Nuclear [MWh] Original resolutions  Lignite [MWh] Original resolutions  \
0                            2291.75                             3154.00
1                             2275.0                             3151.25

   Hard coal [MWh] Original resolutions  \
0                                694.75
1                                683.50

   Fossil gas [MWh] Original resolutions  \
0                                 838.75
1                                 837.50

   Hydro pumped storage [MWh] Original resolutions  \
0                                           542.25
1                                           311.75

  Other conventional [MWh] Original resolutions
0                                         331.0
1                                         331.0

In [3]:
df.head()

,Start date,End date,Biomass [MWh] Original resolutions,Hydropower [MWh] Original resolutions,Wind offshore [MWh] Original resolutions,Wind onshore [MWh] Original resolutions,Photovoltaics [MWh] Original resolutions,Other renewable [MWh] Original resolutions,Nuclear [MWh] Original resolutions,Lignite [MWh] Original resolutions,Hard coal [MWh] Original resolutions,Fossil gas [MWh] Original resolutions,Hydro pumped storage [MWh] Original resolutions,Other conventional [MWh] Original resolutions
0,"Apr 1, 2018 12:00 AM","Apr 1, 2018 12:15 AM",1173.00,422.75,410.00,1743.50,0.0,59.75,2291.75,3154.00,694.75,838.75,542.25,331.0
1,"Apr 1, 2018 12:15 AM","Apr 1, 2018 12:30 AM",1160.00,421.00,399.75,1812.50,0.0,59.75,2275.0,3151.25,683.50,837.50,311.75,331.0
2,"Apr 1, 2018 12:30 AM","Apr 1, 2018 12:45 AM",1155.50,419.50,380.00,1887.25,0.0,59.75,2250.0,3128.75,681.25,841.25,214.00,330.75
3,"Apr 1, 2018 12:45 AM","Apr 1, 2018 1:00 AM",1154.75,420.00,367.75,1921.00,0.0,59.75,2230.5,3052.50,658.25,830.25,156.50,331.5
4,"Apr 1, 2018 1:00 AM","Apr 1, 2018 1:15 AM",1150.00,421.25,354.00,1967.50,0.0,59.75,2219.0,2981.50,597.00,796.25,190.25,330.5

In [ ]:
df.dtypes

Start date                                             str
End date                                               str
Biomass [MWh] Original resolutions                 float64
Hydropower [MWh] Original resolutions              float64
Wind offshore [MWh] Original resolutions           float64
Wind onshore [MWh] Original resolutions            float64
Photovoltaics [MWh] Original resolutions           float64
Other renewable [MWh] Original resolutions         float64
Nuclear [MWh] Original resolutions                  object
Lignite [MWh] Original resolutions                 float64
Hard coal [MWh] Original resolutions               float64
Fossil gas [MWh] Original resolutions              float64
Hydro pumped storage [MWh] Original resolutions    float64
Other conventional [MWh] Original resolutions       object
dtype: object

In [4]:
df = df.rename(columns={
        'Start date': 'timestamp_start',
        'End date': 'timestamp_end',
        'Biomass [MWh] Original resolutions': 'biomass_mwh',
        'Hydropower [MWh] Original resolutions': 'hydro_mwh',
        'Wind offshore [MWh] Original resolutions': 'wind_offshore_mwh',
        'Wind onshore [MWh] Original resolutions': 'wind_onshore_mwh',
        'Photovoltaics [MWh] Original resolutions': 'solar_mwh',
        'Other renewable [MWh] Original resolutions': 'other_renewable_mwh',
        'Nuclear [MWh] Original resolutions': 'nuclear_mwh',
        'Lignite [MWh] Original resolutions': 'lignite_mwh',
        'Hard coal [MWh] Original resolutions': 'hard_coal_mwh',
        'Fossil gas [MWh] Original resolutions': 'gas_mwh',
        'Hydro pumped storage [MWh] Original resolutions': 'hydro_pumped_mwh',
        'Other conventional [MWh] Original resolutions': 'other_conventional_mwh'
    })

In [5]:
print("Nuclear sau rename:")
print(df['nuclear_mwh'].head(3).tolist())
print(f"Nuclear dtype: {df['nuclear_mwh'].dtype}")
print(f"Nuclear mean raw: {pd.to_numeric(df['nuclear_mwh'], errors='coerce').mean():.2f}")

Nuclear sau rename:
[2291.75, 2275.0, 2250.0]
Nuclear dtype: object
Nuclear mean raw: 1416.95

In [ ]:

df['nuclear_mwh'] = pd.to_numeric(
    df['nuclear_mwh'], errors='coerce'
).fillna(0)

df['other_conventional_mwh'] = pd.to_numeric(
    df['other_conventional_mwh'], errors='coerce'
).fillna(0)

#check
print(f"Nuclear mean sau fix: {df['nuclear_mwh'].mean():.2f}")
print(f"Nuclear 2018 sample: {df['nuclear_mwh'].head(5).tolist()}")

Nuclear mean sau fix: 1026.14
Nuclear 2018 sample: [2291.75, 2275.0, 2250.0, 2230.5, 2219.0]

In [ ]:
#change date type
df['timestamp_start'] = pd.to_datetime(df['timestamp_start'])
df['timestamp_end']   = pd.to_datetime(df['timestamp_end'])

In [9]:
# ── Extract time features ─────────────────────────────
df['year']    = df['timestamp_start'].dt.year
df['month']   = df['timestamp_start'].dt.month
df['day']     = df['timestamp_start'].dt.day
df['hour']    = df['timestamp_start'].dt.hour
df['weekday'] = df['timestamp_start'].dt.day_name()
df['season']  = df['month'].map({
    12:'Winter', 1:'Winter',  2:'Winter',
     3:'Spring', 4:'Spring',  5:'Spring',
     6:'Summer', 7:'Summer',  8:'Summer',
     9:'Autumn',10:'Autumn', 11:'Autumn'
})

In [31]:
# ── Derived columns ───────────────────────────────────
df['renewable_mwh'] = (
    df['biomass_mwh'] + df['hydro_mwh'] +
    df['wind_offshore_mwh'] + df['wind_onshore_mwh'] +
    df['solar_mwh'] + df['other_renewable_mwh']
)
df['fossil_mwh'] = (
    df['lignite_mwh'] + df['hard_coal_mwh'] +
    df['gas_mwh'] + df['other_conventional_mwh']
)
df['total_mwh'] = (
    df['renewable_mwh'] + df['fossil_mwh'] + df['nuclear_mwh'] 
)
df['renewable_pct'] = (
    df['renewable_mwh'] / df['total_mwh'] * 100
).round(2)

In [32]:
def classify_green_hour(pct):
    if pct >= 80:
        return 'Very Green'
    elif pct >= 50:
        return 'Green'
    else:
        return 'Not Green'

df['green_label'] = df['renewable_pct'].apply(classify_green_hour)

In [33]:
# ── VERIFY ────────────────────────────────────────────
print(f"Hydro mean:      {df['hydro_mwh'].mean():.2f}")      # ~432
print(f"Avg renewable %: {df['renewable_pct'].mean():.1f}%") # ~47-48%
print(f"NaN check:       {df['renewable_pct'].isna().sum()}") # 0
print(f"\nYearly:")
print(df.groupby('year')['renewable_pct'].mean().round(1))
print(f"\nGreen label:")
print(df['green_label'].value_counts())

Hydro mean:      432.71
Avg renewable %: 48.9%
NaN check:       0

Yearly:
year
2018    38.6
2019    42.8
2020    46.3
2021    41.5
2022    45.9
2023    55.6
2024    58.0
2025    58.2
2026    53.8
Name: renewable_pct, dtype: float64

Green label:
green_label
Not Green     153658
Green         114415
Very Green     14359
Name: count, dtype: int64

In [34]:
print(df.groupby('year')[['renewable_pct','nuclear_mwh']].mean().round(1))

      renewable_pct  nuclear_mwh
year
2018           38.6       2002.6
2019           42.8       2027.5
2020           46.3       1733.9
2021           41.5       1866.6
2022           45.9        936.8
2023           55.6        192.4
2024           58.0          0.0
2025           58.2          0.0
2026           53.8          0.0

In [17]:
df[df['year'] >= 2024]['nuclear_mwh'].describe()

count    80732.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: nuclear_mwh, dtype: float64

In [15]:
df.head()

,timestamp_start,timestamp_end,biomass_mwh,hydro_mwh,wind_offshore_mwh,wind_onshore_mwh,solar_mwh,other_renewable_mwh,nuclear_mwh,lignite_mwh,...,month,day,hour,weekday,season,renewable_mwh,fossil_mwh,total_mwh,renewable_pct,green_label
0,2018-04-01 00:00:00,2018-04-01 00:15:00,1173.00,422.75,410.00,1743.50,0.0,59.75,2291.75,3154.00,...,4,1,0,Sunday,Spring,3809.00,5018.50,11661.50,32.66,Not Green
1,2018-04-01 00:15:00,2018-04-01 00:30:00,1160.00,421.00,399.75,1812.50,0.0,59.75,2275.00,3151.25,...,4,1,0,Sunday,Spring,3853.00,5003.25,11443.00,33.67,Not Green
2,2018-04-01 00:30:00,2018-04-01 00:45:00,1155.50,419.50,380.00,1887.25,0.0,59.75,2250.00,3128.75,...,4,1,0,Sunday,Spring,3902.00,4982.00,11348.00,34.38,Not Green
3,2018-04-01 00:45:00,2018-04-01 01:00:00,1154.75,420.00,367.75,1921.00,0.0,59.75,2230.50,3052.50,...,4,1,0,Sunday,Spring,3923.25,4872.50,11182.75,35.08,Not Green
4,2018-04-01 01:00:00,2018-04-01 01:15:00,1150.00,421.25,354.00,1967.50,0.0,59.75,2219.00,2981.50,...,4,1,1,Sunday,Spring,3952.50,4705.25,11067.00,35.71,Not Green

In [35]:
df.groupby('year')[['renewable_mwh','fossil_mwh','nuclear_mwh','total_mwh']].mean()

      renewable_mwh   fossil_mwh  nuclear_mwh     total_mwh
year
2018    5832.871487  6973.366526  2002.604880  14808.842893
2019    6373.442245  6232.560203  2027.459025  14633.461473
2020    6638.909416  5652.931495  1733.944850  14025.785761
2021    6117.631378  6371.666296  1866.609204  14355.906878
2022    6657.931364  6384.396911   936.771390  13979.099665
2023    7180.119043  5280.886152   192.372695  12653.377890
2024    7291.211101  4869.074190     0.000000  12160.285291
2025    7356.062651  4858.597278     0.000000  12214.659928
2026    7695.058796  6208.024249     0.000000  13903.083045

In [ ]:
# ── Save fct_summary ───
fct_summary = df[[
    'timestamp_start', 'year', 'month', 'day', 'hour',
    'weekday', 'season',
    'biomass_mwh', 'hydro_mwh', 'wind_offshore_mwh',
    'wind_onshore_mwh', 'solar_mwh', 'other_renewable_mwh',
    'nuclear_mwh', 'lignite_mwh', 'hard_coal_mwh',
    'gas_mwh', 'hydro_pumped_mwh', 'other_conventional_mwh',
    'renewable_mwh', 'fossil_mwh', 'total_mwh',
    'renewable_pct', 'green_label'
]].copy()

In [37]:
# ── dim_time ──────────────────────────────────────────
dim_time = df[[
    'timestamp_start', 'year', 'month', 'day',
    'hour', 'weekday', 'season'
]].drop_duplicates().reset_index(drop=True)
dim_time.insert(0, 'time_id', range(1, len(dim_time) + 1))

In [38]:
# ── dim_energy_source ─────────────────────────────────
dim_energy_source = pd.DataFrame({
    'source_id':   range(1, 13),
    'source_name': ['Biomass','Hydropower','Wind Offshore',
                    'Wind Onshore','Solar','Other Renewable',
                    'Nuclear','Lignite','Hard Coal',
                    'Fossil Gas','Other Conventional',  'Hydro Pumped Storage'],
    'source_type': ['Renewable','Renewable','Renewable',
                    'Renewable','Renewable','Renewable',
                    'Nuclear','Fossil','Fossil','Fossil','Fossil', 'Storage'],
    'is_renewable':[True,True,True,True,True,True,
                    False,False,False,False,False,False]
})

In [39]:
# ── fct_generation (long format) ─────────────────────
source_col_map = {
    'biomass_mwh':           'Biomass',
    'hydro_mwh':             'Hydropower',
    'wind_offshore_mwh':     'Wind Offshore',
    'wind_onshore_mwh':      'Wind Onshore',
    'solar_mwh':             'Solar',
    'other_renewable_mwh':   'Other Renewable',
    'nuclear_mwh':           'Nuclear',
    'lignite_mwh':           'Lignite',
    'hard_coal_mwh':         'Hard Coal',
    'gas_mwh':               'Fossil Gas',
    'other_conventional_mwh':'Other Conventional',
    'hydro_pumped_mwh': 'Hydro Pumped Storage'
}

fct_gen = df[['timestamp_start'] + list(source_col_map.keys())].melt(
    id_vars='timestamp_start',
    var_name='col_name',
    value_name='generation_mwh'
)
fct_gen['source_name'] = fct_gen['col_name'].map(source_col_map)
fct_gen = fct_gen.merge(
    dim_energy_source[['source_id','source_name']], on='source_name')
fct_gen = fct_gen.merge(
    dim_time[['time_id','timestamp_start']], on='timestamp_start')
fct_gen = fct_gen[['time_id','source_id','generation_mwh']]

In [ ]:
import os

os.makedirs('data/processed', exist_ok=True)

# Save lại
fct_summary.to_csv('data/processed/fct_summary.csv', index=False)
fct_gen.to_csv('data/processed/fct_generation.csv', index=False)
dim_time.to_csv('data/processed/dim_time.csv', index=False)
dim_energy_source.to_csv('data/processed/dim_energy_source.csv', index=False)

print("Done saving CSV")

Done saving CSV

In [ ]:
import pandas as pd

# Load & check
fct = pd.read_csv('data/processed/fct_summary.csv')
dim_s = pd.read_csv('data/processed/dim_energy_source.csv')
dim_t = pd.read_csv('data/processed/dim_time.csv')
fct_g = pd.read_csv('data/processed/fct_generation.csv')

In [ ]:
print("=== Shape ===")
print(f"fct_summary:      {fct.shape}")
print(f"fct_generation:   {fct_g.shape}")
print(f"dim_time:         {dim_t.shape}")
print(f"dim_energy_source:{dim_s.shape}")

print("\n=== fct_summary sample ===")
print(fct[['timestamp_start','renewable_mwh',
           'total_mwh','renewable_pct']].head(3))

print("\n=== dim_energy_source ===")
print(dim_s)

=== Shape ===
fct_summary:      (282432, 24)
fct_generation:   (3389184, 3)
dim_time:         (282400, 8)
dim_energy_source:(12, 4)

=== fct_summary sample ===
       timestamp_start  renewable_mwh  total_mwh  renewable_pct
0  2018-04-01 00:00:00         3809.0    9038.75          42.14
1  2018-04-01 00:15:00         3853.0    8837.00          43.60
2  2018-04-01 00:30:00         3902.0    8767.25          44.51

=== dim_energy_source ===
    source_id           source_name source_type  is_renewable
0           1               Biomass   Renewable          True
1           2            Hydropower   Renewable          True
2           3         Wind Offshore   Renewable          True
3           4          Wind Onshore   Renewable          True
4           5                 Solar   Renewable          True
5           6       Other Renewable   Renewable          True
6           7               Nuclear     Nuclear         False
7           8               Lignite      Fossil         False
8           9             Hard Coal      Fossil         False
9          10            Fossil Gas      Fossil         False
10         11    Other Conventional      Fossil         False
11         12  Hydro Pumped Storage     Storage         False

In [ ]:
print(fct_summary.columns.tolist())

['timestamp_start', 'year', 'month', 'day', 'hour', 'weekday', 'season', 'biomass_mwh', 'hydro_mwh', 'wind_offshore_mwh', 'wind_onshore_mwh', 'solar_mwh', 'other_renewable_mwh', 'nuclear_mwh', 'lignite_mwh', 'hard_coal_mwh', 'gas_mwh', 'hydro_pumped_mwh', 'other_conventional_mwh', 'renewable_mwh', 'fossil_mwh', 'total_mwh', 'renewable_pct', 'green_label']

In [ ]:
from sqlalchemy import create_engine
import pandas as pd


engine = create_engine(
    'postgresql://postgres:'
)

# Test connection trước
try:
    with engine.connect() as conn:
        print("Connection OK ✓")
except Exception as e:
    print(f"Connection failed: {e}")

Connection OK ✓

In [ ]:
print("Uploading dim_energy_source...")
dim_energy_source.to_sql('dim_energy_source', engine,
                          if_exists='replace', index=False)
print(f"✓ dim_energy_source: {len(dim_energy_source):,} rows")

print("Uploading dim_time...")
dim_time.to_sql('dim_time', engine,
                if_exists='replace', index=False)
print(f"✓ dim_time: {len(dim_time):,} rows")

print("Uploading fct_summary...")
fct_summary.to_sql('fct_summary', engine,
                   if_exists='replace', index=False,
                   chunksize=10000)
print(f"✓ fct_summary: {len(fct_summary):,} rows")

print("\n All done!")

Uploading dim_energy_source...
✓ dim_energy_source: 12 rows
Uploading dim_time...
✓ dim_time: 282,400 rows
Uploading fct_summary...
✓ fct_summary: 282,432 rows

✅ All done!

In [ ]:
thresholds = [50, 60, 65, 70, 75, 80]

for t in thresholds:
    count = (df['renewable_pct'] >= t).sum()
    pct = count / len(df) * 100
    print(f">= {t}%: {count:,} hours ({pct:.1f}% of all hours)")

>= 50%: 110,761 hours (39.2% of all hours)
>= 60%: 70,086 hours (24.8% of all hours)
>= 65%: 52,536 hours (18.6% of all hours)
>= 70%: 36,655 hours (13.0% of all hours)
>= 75%: 23,916 hours (8.5% of all hours)
>= 80%: 14,652 hours (5.2% of all hours)